version: '3'

services:
  ubuntu:
    image: accetto/ubuntu-vnc-xfce-g3:latest
    environment:
      - NOVNC_HEARTBEAT=5
    ports:
      - 6901:6901
    cap_add:
      - SYS_ADMIN
    #user: 0
    
